"""Exact, provenance-aware source retention beneath Work Buddy domains.

The public API stays at this package boundary so Truth, Co-work, Journal, and
Agent Execution never reach into the Sources SQLite schema directly.
"""

from work_buddy.sources.disclosure import (
    CapturedDisclosureSource,
    SourcesDisclosureService,
)
from work_buddy.sources.conversation import (
    ConversationMessageProvider,
    conversation_origin,
)
from work_buddy.sources.cowork import (
    COWORK_DOCUMENT_PROVIDER_ID,
    CoworkActionSnapshotProvider,
    cowork_action_snapshot_origin,
)
from work_buddy.sources.dispatch import OutboxDispatcher, SourceOutbox
from work_buddy.sources.errors import (
    InvalidSourceReference,
    InvalidSourceRequest,
    SourceAccessDenied,
    SourceAuthorityMismatch,
    SourceError,
    SourceExportDenied,
    SourceIdempotencyConflict,
    SourceImportCollision,
    SourceImportInvalid,
    SourceIntegrityFailure,
    SourceLeaseConflict,
    SourceNotFound,
    SourceOriginMismatch,
    SourceProviderConflict,
    SourceProviderNotFound,
    SourceRedacted,
    SourceUsageConflict,
    public_error,
)
from work_buddy.sources.export import (
    abort_source_export,
    ExportAuthorization,
    ExportResult,
    ImportAuthorization,
    ImportResult,
    export_sources,
    import_sources,
    record_source_export_operator_authorization,
    recover_source_export,
    source_export_recovery_scope,
    source_export_status,
)
from work_buddy.sources.ingress import (
    DomainCommand,
    HumanInputCommit,
    HumanInputRequest,
    TrustedIngressContext,
    TrustedIngressService,
)
from work_buddy.sources.models import (
    AccessBinding,
    ActorRef,
    AttributionAssertion,
    EffectReceipt,
    OriginRef,
    OutboxEffect,
    RedactionResult,
    ResolvedSource,
    SourceDerivation,
    SourceItem,
    SourceObservation,
    SourceRef,
    SourceRepresentation,
    SourceResolutionRecord,
    UsageReservation,
)
from work_buddy.sources.providers import (
    NativeCapture,
    NativeObservation,
    ProviderRegistry,
    SourceProvider,
    reobserve_origin,
    source_capture_from_origin,
)
from work_buddy.sources.redact import redact_source
from work_buddy.sources.resolve import (
    ReservedResolution,
    resolve_and_reserve_source,
    resolve_source,
)
from work_buddy.sources.store import SourceStore, SourcesPaths


__all__ = [
    "AccessBinding",
    "ActorRef",
    "AttributionAssertion",
    "CapturedDisclosureSource",
    "COWORK_DOCUMENT_PROVIDER_ID",
    "ConversationMessageProvider",
    "CoworkActionSnapshotProvider",
    "DomainCommand",
    "EffectReceipt",
    "ExportAuthorization",
    "ExportResult",
    "HumanInputCommit",
    "HumanInputRequest",
    "ImportAuthorization",
    "ImportResult",
    "InvalidSourceReference",
    "InvalidSourceRequest",
    "NativeCapture",
    "NativeObservation",
    "OriginRef",
    "OutboxDispatcher",
    "OutboxEffect",
    "ProviderRegistry",
    "RedactionResult",
    "ReservedResolution",
    "ResolvedSource",
    "SourceAccessDenied",
    "SourceAuthorityMismatch",
    "SourceDerivation",
    "SourceError",
    "SourceExportDenied",
    "SourceIdempotencyConflict",
    "SourceImportCollision",
    "SourceImportInvalid",
    "SourceIntegrityFailure",
    "SourceItem",
    "SourceLeaseConflict",
    "SourceNotFound",
    "SourceObservation",
    "SourceOriginMismatch",
    "SourceOutbox",
    "SourceProvider",
    "SourceProviderConflict",
    "SourceProviderNotFound",
    "SourceRedacted",
    "SourceRef",
    "SourceRepresentation",
    "SourceResolutionRecord",
    "SourceStore",
    "SourceUsageConflict",
    "SourcesDisclosureService",
    "SourcesPaths",
    "TrustedIngressContext",
    "TrustedIngressService",
    "UsageReservation",
    "abort_source_export",
    "export_sources",
    "conversation_origin",
    "cowork_action_snapshot_origin",
    "import_sources",
    "recover_source_export",
    "record_source_export_operator_authorization",
    "source_export_recovery_scope",
    "source_export_status",
    "public_error",
    "reobserve_origin",
    "redact_source",
    "resolve_and_reserve_source",
    "resolve_source",
    "source_capture_from_origin",
]
