import { expect, test } from "@playwright/test"
import { openCowork } from "./cowork-helpers"

test("demo Truth claims are discoverable from marks and the shared passage menu", { tag: "@no-ci" }, async ({ page }) => {
  await openCowork(page)
  await page.getByRole("tab", { name: "Truth", exact: true }).click()
  const marks = page.locator("[data-wb-anchor-kind='expression']")
  await expect(marks).toHaveCount(5)
  await expect(page.getByLabel("Truth mark legend")).toContainText("4 claims in view")
  await expect(page.getByLabel("Truth mark legend")).toContainText("1 fact")
  const fact = marks.filter({ hasText: "cold-start latency" })
  await expect(fact).toHaveCSS("text-decoration-style", "solid")
  await expect(marks.filter({ hasText: "always rebuild" })).toHaveCSS("text-decoration-style", "dashed")
  await expect(marks.filter({ hasText: "A collector records" })).toHaveCSS("text-decoration-style", "dotted")
  await fact.hover()
  const card = page.getByRole("complementary", { name: "Claim at this passage" })
  await expect(card).toContainText("2 evidence receipts")
  await card.getByRole("button", { name: "Open in Truth" }).click()
  await expect(page.getByRole("region", { name: "Claim details" })).toContainText("current fact")
  await marks.filter({ hasText: "always rebuild" }).click()
  await expect(page.getByRole("region", { name: "Claim details" })).toContainText("No evidence recorded")
  await page.getByRole("tab", { name: /^Chat/ }).click()
  await expect(marks).toHaveCount(0)
  const paragraph = page.locator(".tiptap p").filter({ hasText: "cold-start latency" })
  await paragraph.selectText()
  await page.getByRole("button", { name: "Passage actions", exact: true }).click()
  await expect(page.getByRole("menuitem", { name: /^Show claim/ })).toHaveCount(2)
  await page.getByRole("menuitem", { name: /^Ask about this part/ }).click()
  await expect(page.locator(".wb-cowork-chat-target")).not.toContainText("Whole document")
  await paragraph.click()
  await page.keyboard.press("Shift+F10")
  await expect(page.getByRole("menu", { name: "Actions for this passage" })).toBeVisible()
  await page.keyboard.press("Escape")
  await expect(page.locator(".tiptap")).toBeFocused()
})

test("demo mobile selection handle opens the Truth pane", { tag: "@no-ci" }, async ({ page }) => {
  await openCowork(page)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole("tab", { name: "Truth", exact: true }).click()
  await page.getByRole("tab", { name: "Editor", exact: true }).click()
  const editor = page.getByRole("textbox", { name: "Document editor", exact: true })
  await expect(editor).toBeVisible()
  await editor.focus()
  await expect(editor).toBeFocused()
  await page.locator(".tiptap p").filter({ hasText: "A collector records" }).selectText()
  await expect(page.getByRole("button", { name: "Set by selection", exact: true })).toBeEnabled()
  await page.getByRole("button", { name: "Passage actions", exact: true }).click()
  await page.getByRole("menuitem", { name: /^Show claim/ }).click()
  await expect(page.getByRole("tab", { name: "Truth", exact: true })).toHaveAttribute("aria-selected", "true")
  await expect(page.getByRole("region", { name: "Claim details" })).toBeVisible()
  await expect(page.getByRole("button", { name: "Passage actions", exact: true })).toHaveCount(0)
})
