import {
  Input,
  Label,
  Text,
  TextField,
} from "react-aria-components";
import { useState } from "react";

import { SelectField, type SelectFieldOption } from "../../../ui";
import type { HelpContent } from "../../../dashboard/help";
import {
  COWORK_PROVENANCE_DETERMINATION_SCHEMA,
  currentCoworkUser,
  type CoworkProvenanceActorIdentity,
  type CoworkProvenanceAuthorshipKind,
  type CoworkProvenanceDetermination,
  type CoworkProvenancePerson,
  type CoworkProvenanceReviewStatus,
} from "./contracts";
import "./styles.css";

const AUTHORSHIP_OPTIONS: readonly SelectFieldOption<CoworkProvenanceAuthorshipKind>[] =
  [
    {
      value: "human",
      label: "Human-written",
      description: "Created by one or more people.",
    },
    {
      value: "ai",
      label: "AI-written",
      description: "Generated by an AI system.",
    },
    {
      value: "mixed",
      label: "Human and AI",
      description: "Both a person and AI contributed.",
    },
    {
      value: "unknown",
      label: "Unknown",
      description: "The authorship is not known.",
    },
  ];

type PersonChoice = CoworkProvenancePerson["kind"];

const PERSON_OPTIONS: readonly SelectFieldOption<PersonChoice>[] = [
  { value: "current_user", label: "Me" },
  { value: "named_person", label: "Someone else" },
];

const REVIEW_OPTIONS: readonly SelectFieldOption<
  Exclude<CoworkProvenanceReviewStatus, "not_applicable">
>[] = [
  {
    value: "reviewed",
    label: "Reviewed by a person",
    description: "A person read and reviewed this text.",
  },
  {
    value: "not_reviewed",
    label: "Not reviewed",
    description: "No person has reviewed it yet.",
  },
];

const AUTHORSHIP_HELP: HelpContent = {
  summary: "Record who created this text.",
  details:
    "Authorship is separate from accuracy: text can be human-written, AI-written, mixed, or unknown.",
};

const REVIEW_HELP: HelpContent = {
  summary: "Record whether a person reviewed AI-written text.",
  details:
    "A review records that a named person read the text; it does not claim that every statement is correct.",
};

const AUTHOR_HELP: HelpContent = {
  summary: "Identify the human author.",
  details:
    "“Me” means the current local dashboard actor. A typed name is recorded as a claimed identity, not a verified account.",
};

const REVIEWER_HELP: HelpContent = {
  summary: "Identify the human reviewer.",
  details:
    "“Me” means the current local dashboard actor. A typed name is recorded as a claimed identity, not a verified account.",
};

const primaryPerson = (
  people: readonly CoworkProvenancePerson[],
  currentUserIdentity: CoworkProvenanceActorIdentity,
): CoworkProvenancePerson =>
  people[0] ?? currentCoworkUser(currentUserIdentity);

const replacePrimaryPerson = (
  people: readonly CoworkProvenancePerson[],
  person: CoworkProvenancePerson,
): readonly CoworkProvenancePerson[] => [person, ...people.slice(1)];

const personForChoice = (
  choice: PersonChoice,
  currentUserIdentity: CoworkProvenanceActorIdentity,
): CoworkProvenancePerson =>
  choice === "current_user"
    ? currentCoworkUser(currentUserIdentity)
    : { kind: "named_person", display_name: "" };

const reviewForStatus = (
  status: Exclude<CoworkProvenanceReviewStatus, "not_applicable">,
  priorReviewers: readonly CoworkProvenancePerson[],
  currentUserIdentity: CoworkProvenanceActorIdentity,
): CoworkProvenanceDetermination["human_review"] =>
  status === "reviewed"
    ? {
        status,
        reviewers:
          priorReviewers.length === 0
            ? [currentCoworkUser(currentUserIdentity)]
            : priorReviewers,
      }
    : { status, reviewers: [] };

export interface CoworkProvenanceFormProps {
  readonly value: CoworkProvenanceDetermination;
  readonly currentUserIdentity: CoworkProvenanceActorIdentity;
  readonly disabled?: boolean;
  readonly idPrefix?: string;
  onChange(value: CoworkProvenanceDetermination): void;
}

/**
 * Shared authorship and human-review form. File import embeds this component in
 * its own flow; substantial paste wraps it in the modal below.
 */
export function CoworkProvenanceForm({
  value,
  currentUserIdentity,
  disabled = false,
  idPrefix = "wb-cowork-provenance",
  onChange,
}: CoworkProvenanceFormProps) {
  const [authorNameTouched, setAuthorNameTouched] = useState(false);
  const [reviewerNameTouched, setReviewerNameTouched] = useState(false);
  const authorship = value.authorship.kind;
  const asksForHumanAuthor = authorship === "human" || authorship === "mixed";
  const asksForReview = authorship === "ai" || authorship === "mixed";
  const author = primaryPerson(
    value.authorship.contributors,
    currentUserIdentity,
  );
  const reviewers =
    value.human_review.status === "reviewed"
      ? value.human_review.reviewers
      : [];
  const reviewer = primaryPerson(reviewers, currentUserIdentity);

  const updateAuthorship = (kind: CoworkProvenanceAuthorshipKind): void => {
    setAuthorNameTouched(false);
    setReviewerNameTouched(false);
    const contributors =
      kind === "human" || kind === "mixed"
        ? value.authorship.contributors.length === 0
          ? [currentCoworkUser(currentUserIdentity)]
          : value.authorship.contributors
        : [];
    const human_review: CoworkProvenanceDetermination["human_review"] =
      kind === "human"
        ? { status: "not_applicable", reviewers: [] }
        : kind === "unknown"
          ? { status: "not_applicable", reviewers: [] }
          : value.human_review.status === "not_applicable"
            ? { status: "not_reviewed", reviewers: [] }
            : value.human_review;
    onChange({
      schema: COWORK_PROVENANCE_DETERMINATION_SCHEMA,
      authorship: { kind, contributors },
      human_review,
    });
  };

  const updateAuthor = (person: CoworkProvenancePerson): void => {
    onChange({
      ...value,
      authorship: {
        ...value.authorship,
        contributors: replacePrimaryPerson(
          value.authorship.contributors,
          person,
        ),
      },
    });
  };

  const updateReviewStatus = (
    status: Exclude<CoworkProvenanceReviewStatus, "not_applicable">,
  ): void => {
    onChange({
      ...value,
      human_review: reviewForStatus(
        status,
        reviewers,
        currentUserIdentity,
      ),
    });
  };

  const updateReviewer = (person: CoworkProvenancePerson): void => {
    onChange({
      ...value,
      human_review: {
        status: "reviewed",
        reviewers: replacePrimaryPerson(reviewers, person),
      },
    });
  };

  return (
    <div className="wb-cowork-provenance-form">
      <SelectField
        label="Authorship"
        value={authorship}
        options={AUTHORSHIP_OPTIONS}
        help={AUTHORSHIP_HELP}
        disabled={disabled}
        onChange={updateAuthorship}
      />

      {asksForHumanAuthor ? (
        <>
          <SelectField
            label={authorship === "mixed" ? "Human contributor" : "Author"}
            value={author.kind}
            options={PERSON_OPTIONS}
            help={AUTHOR_HELP}
            disabled={disabled}
            onChange={(choice) => {
              setAuthorNameTouched(false);
              updateAuthor(personForChoice(choice, currentUserIdentity));
            }}
          />
          {author.kind === "named_person" ? (
            <TextField
              className="wb-cowork-field"
              value={author.display_name}
              isDisabled={disabled}
              isInvalid={
                authorNameTouched &&
                author.display_name.trim().length === 0
              }
              onBlur={() => setAuthorNameTouched(true)}
              onChange={(display_name) =>
                updateAuthor({ kind: "named_person", display_name })
              }
            >
              <Label htmlFor={`${idPrefix}-author-name`}>Author’s name</Label>
              <Input id={`${idPrefix}-author-name`} />
              {authorNameTouched &&
              author.display_name.trim().length === 0 ? (
                <Text slot="errorMessage">Enter the author’s name.</Text>
              ) : null}
            </TextField>
          ) : null}
        </>
      ) : null}

      {asksForReview ? (
        <>
          <SelectField
            label="Human review"
            value={
              value.human_review.status === "not_applicable"
                ? "not_reviewed"
                : value.human_review.status
            }
            options={REVIEW_OPTIONS}
            help={REVIEW_HELP}
            disabled={disabled}
            onChange={updateReviewStatus}
          />
          {value.human_review.status === "reviewed" ? (
            <>
              <SelectField
                label="Reviewer"
                value={reviewer.kind}
                options={PERSON_OPTIONS}
                help={REVIEWER_HELP}
                disabled={disabled}
                onChange={(choice) => {
                  setReviewerNameTouched(false);
                  updateReviewer(
                    personForChoice(choice, currentUserIdentity),
                  );
                }}
              />
              {reviewer.kind === "named_person" ? (
                <TextField
                  className="wb-cowork-field"
                  value={reviewer.display_name}
                  isDisabled={disabled}
                  isInvalid={
                    reviewerNameTouched &&
                    reviewer.display_name.trim().length === 0
                  }
                  onBlur={() => setReviewerNameTouched(true)}
                  onChange={(display_name) =>
                    updateReviewer({ kind: "named_person", display_name })
                  }
                >
                  <Label htmlFor={`${idPrefix}-reviewer-name`}>
                    Reviewer’s name
                  </Label>
                  <Input id={`${idPrefix}-reviewer-name`} />
                  {reviewerNameTouched &&
                  reviewer.display_name.trim().length === 0 ? (
                    <Text slot="errorMessage">
                      Enter the reviewer’s name.
                    </Text>
                  ) : null}
                </TextField>
              ) : null}
            </>
          ) : null}
        </>
      ) : null}
    </div>
  );
}
