"""Build script: generate CapabilityUnit entries from the live registry.

Reads the MCP registry and produces PromptUnit-compatible JSON that can
be merged into the knowledge store. This is the bridge between the
Python-defined capabilities and the canonical JSON store.

Workflow definitions live directly in the knowledge store as hand-authored
content (knowledge/store/workflows.json). They are NOT generated by this
script. The conductor reads them at runtime via ``_discover_workflows_from_store()``.

Usage:
    python -m work_buddy.knowledge.build [--write]

Without --write, prints the generated JSON to stdout.
With --write, writes to knowledge/store/_generated_capabilities.json.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

from work_buddy.logging_config import get_logger

logger = get_logger(__name__)

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent

# Cache for unfiltered registry (built once per process)
_UNFILTERED: dict | None = None


def _get_unfiltered_registry() -> dict:
    """Build the registry WITHOUT filtering out capabilities with unmet tool requirements.

    The knowledge store should document ALL capabilities regardless of
    whether their tools (Obsidian, Hindsight, etc.) are currently available.
    """
    global _UNFILTERED  # noqa: PLW0603
    if _UNFILTERED is not None:
        return _UNFILTERED

    from work_buddy.mcp_server.registry import (
        Capability,
        _messaging_capabilities, _contract_capabilities, _status_capabilities,
        _journal_capabilities, _memory_capabilities, _task_capabilities,
        _context_capabilities, _project_capabilities, _sidecar_capabilities,
        _llm_capabilities, _consent_capabilities, _notification_capabilities,
        _thread_capabilities, _remote_session_capabilities, _ledger_capabilities,
    )

    registry: dict[str, Capability] = {}

    for label, fn in [
        ("messaging", _messaging_capabilities),
        ("contracts", _contract_capabilities),
        ("status", _status_capabilities),
        ("journal", _journal_capabilities),
        ("memory", _memory_capabilities),
        ("tasks", _task_capabilities),
        ("context", _context_capabilities),
        ("projects", _project_capabilities),
        ("sidecar", _sidecar_capabilities),
        ("llm", _llm_capabilities),
        ("consent", _consent_capabilities),
        ("notifications", _notification_capabilities),
        ("threads", _thread_capabilities),
        ("remote_session", _remote_session_capabilities),
        ("ledger", _ledger_capabilities),
    ]:
        try:
            for cap in fn():
                registry[cap.name] = cap
        except Exception as e:
            logger.warning("Failed to load %s capabilities: %s", label, e)

    _UNFILTERED = registry
    logger.info("Unfiltered registry: %d entries", len(registry))
    return registry
_STORE_DIR = _REPO_ROOT / "knowledge" / "store"

# Map registry categories to store path prefixes
_CATEGORY_PATH_MAP = {
    "tasks": "tasks",
    "contracts": "contracts",
    "projects": "projects",
    "journal": "journal",
    "context": "context",
    "memory": "memory",
    "messaging": "messaging",
    "notifications": "notifications",
    "consent": "notifications/consent",
    "threads": "threads",
    "status": "status",
    "sidecar": "status",
    "llm": "status",
}


def build_capability_units() -> dict[str, dict[str, Any]]:
    """Generate CapabilityUnit dicts from the MCP registry.

    Uses _build_registry_unfiltered() to include ALL capabilities,
    even those whose tool requirements (Obsidian, Hindsight, etc.)
    aren't currently met. The store should document everything,
    not just what's available right now.
    """
    from work_buddy.mcp_server.registry import Capability
    reg = _get_unfiltered_registry()
    units: dict[str, dict[str, Any]] = {}

    for name, entry in sorted(reg.items()):
        if not isinstance(entry, Capability):
            continue

        # Skip the knowledge system's own capabilities (already in store manually)
        if name in ("agent_docs", "agent_docs_rebuild", "docs_query", "docs_get", "docs_index"):
            continue

        category = entry.category
        prefix = _CATEGORY_PATH_MAP.get(category, category)
        path = f"{prefix}/{name}"

        unit: dict[str, Any] = {
            "kind": "capability",
            "name": _humanize(name),
            "description": entry.description,
            "capability_name": name,
            "category": category,
        }

        if entry.search_aliases:
            unit["aliases"] = entry.search_aliases
        if entry.parameters:
            unit["parameters"] = entry.parameters
        if entry.requires:
            unit["requires"] = entry.requires
        if entry.mutates_state:
            unit["mutates_state"] = True
            unit["retry_policy"] = entry.retry_policy

        # Check for consent requirement
        if hasattr(entry.callable, '_requires_consent'):
            unit["consent_required"] = True

        # Tags from category + name parts
        unit["tags"] = _name_to_tags(name, category)

        # Parent path
        unit["parents"] = [prefix]

        units[path] = unit

    return units


def build_parent_stubs(
    cap_units: dict[str, dict],
) -> dict[str, dict[str, Any]]:
    """Generate parent container nodes for categories that don't have them yet."""
    from work_buddy.knowledge.store import load_store

    existing = load_store()
    all_units = {**cap_units}

    # Collect all parent paths referenced
    parent_paths: dict[str, list[str]] = {}
    for path, unit in all_units.items():
        for parent in unit.get("parents", []):
            parent_paths.setdefault(parent, []).append(path)

    stubs: dict[str, dict[str, Any]] = {}
    for parent_path, child_paths in parent_paths.items():
        if parent_path in existing:
            # Parent already exists in hand-authored store — skip
            continue
        if parent_path in stubs:
            # Already created a stub — just extend children
            stubs[parent_path]["children"] = sorted(
                set(stubs[parent_path].get("children", []) + child_paths)
            )
            continue

        stubs[parent_path] = {
            "kind": "system",
            "name": _humanize(parent_path.rsplit("/", 1)[-1]),
            "description": f"{_humanize(parent_path.rsplit('/', 1)[-1])} capabilities and workflows",
            "tags": [parent_path.replace("/", " ")],
            "children": sorted(child_paths),
            "content": {
                "summary": f"Container for {len(child_paths)} capabilities and workflows.",
            },
        }

    return stubs


def _humanize(name: str) -> str:
    """Convert slug to human-readable: task_create → Task Create."""
    return name.replace("_", " ").replace("-", " ").title()


def _name_to_tags(name: str, category: str) -> list[str]:
    """Extract search tags from a capability/workflow name."""
    parts = name.replace("-", "_").split("_")
    tags = [category] + [p for p in parts if p != category]
    return list(dict.fromkeys(tags))  # dedupe preserving order


def build_all(write: bool = False) -> dict[str, Any]:
    """Build all generated units and optionally write to store files.

    Generates capability entries only. Workflow definitions live in
    knowledge/store/workflows.json as hand-authored content.
    """
    caps = build_capability_units()
    stubs = build_parent_stubs(caps)

    result = {
        "capabilities": len(caps),
        "parent_stubs": len(stubs),
    }

    if write:
        _STORE_DIR.mkdir(parents=True, exist_ok=True)

        # Write capabilities
        cap_path = _STORE_DIR / "_generated_capabilities.json"
        cap_path.write_text(json.dumps(caps, indent=2, ensure_ascii=False), encoding="utf-8")
        result["capabilities_file"] = str(cap_path)

        # Write parent stubs (only new ones)
        if stubs:
            stub_path = _STORE_DIR / "_generated_parents.json"
            stub_path.write_text(json.dumps(stubs, indent=2, ensure_ascii=False), encoding="utf-8")
            result["parents_file"] = str(stub_path)

        logger.info(
            "Generated store files: %d capabilities, %d parent stubs",
            len(caps), len(stubs),
        )

    return result


if __name__ == "__main__":
    write = "--write" in sys.argv
    docs = "--docs" in sys.argv
    result = build_all(write=write)

    if docs:
        # Also generate documentation site
        from work_buddy.knowledge.store import invalidate_store
        invalidate_store()  # reload with freshly generated store files
        from work_buddy.knowledge.docs_gen import generate_docs
        docs_result = generate_docs(write=write)
        result["docs"] = docs_result

    print(json.dumps(result, indent=2))
