"""Build script: generate CapabilityUnit entries from the live registry.

Reads the MCP registry and produces PromptUnit-compatible JSON that can
be merged into the knowledge store. This is the bridge between the
Python-defined capabilities and the canonical JSON store.

Workflow definitions live directly in the knowledge store as hand-authored
content (knowledge/store/workflows.json). They are NOT generated by this
script. The conductor reads them at runtime via ``_discover_workflows_from_store()``.

Usage (run from the complete ``work-buddy`` conda env — see CLAUDE.md,
"Running Python in this repo" — because the unfiltered registry imports
every capability category, including ones with optional dependencies):

    conda run -n work-buddy python -m work_buddy.knowledge.build [--write]

Without --write, prints the generated JSON to stdout.
With --write, writes to knowledge/store/_generated_capabilities.json.

Note: the running MCP gateway also regenerates these files on startup
in a background thread (see ``mcp_server/server.py``), and
``tests/unit/test_generated_capabilities_in_sync.py`` fails if the
committed files drift from the registry — so a manual run is rarely
needed, mainly to refresh the committed files before a commit.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

from work_buddy.logging_config import get_logger

logger = get_logger(__name__)

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent

# Cache for unfiltered registry (built once per process)
_UNFILTERED: dict | None = None

# Top-level domains whose generated parent stub should be classified as
# ``system`` (coherent functional domain whose persistent state work-buddy
# owns) rather than the default ``concept`` (category heading for
# capabilities/workflows). Anything not listed here defaults to ``concept``.
# Adding a new top-level system domain → add it here.
_SYSTEM_PARENT_DOMAINS: set[str] = {
    "artifacts",
    "contracts",
    "conversations",
    "journal",
    "memory",     # work-buddy memory layer (Hindsight integration is a future split)
    "messaging",
    "tasks",
    "triage",
    # See knowledge/store/*.json hand-authored entries for additional system
    # domains (e.g. clarify, daily-journal, inline, notifications, projects,
    # threads); those are not generated stubs because they have hand-authored
    # parent docs.
}


def _get_unfiltered_registry() -> dict:
    """Build the registry WITHOUT filtering out capabilities with unmet tool requirements.

    The knowledge store should document ALL capabilities regardless of
    whether their tools (Obsidian, Hindsight, etc.) are currently available.
    """
    global _UNFILTERED  # noqa: PLW0603
    if _UNFILTERED is not None:
        return _UNFILTERED

    from work_buddy.mcp_server.registry import (
        Capability,
        _messaging_capabilities, _contract_capabilities, _status_capabilities,
        _journal_capabilities, _memory_capabilities, _task_capabilities,
        _context_capabilities, _project_capabilities, _sidecar_capabilities,
        _llm_capabilities, _consent_capabilities, _notification_capabilities,
        _conversation_capabilities, _remote_session_capabilities, _ledger_capabilities,
        _artifact_capabilities, _knowledge_capabilities,
    )

    registry: dict[str, Capability] = {}

    for label, fn in [
        ("messaging", _messaging_capabilities),
        ("contracts", _contract_capabilities),
        ("status", _status_capabilities),
        ("journal", _journal_capabilities),
        ("memory", _memory_capabilities),
        ("tasks", _task_capabilities),
        ("context", _context_capabilities),
        ("projects", _project_capabilities),
        ("sidecar", _sidecar_capabilities),
        ("llm", _llm_capabilities),
        ("consent", _consent_capabilities),
        ("notifications", _notification_capabilities),
        ("conversations", _conversation_capabilities),
        ("remote_session", _remote_session_capabilities),
        ("ledger", _ledger_capabilities),
        ("artifacts", _artifact_capabilities),
        ("knowledge", _knowledge_capabilities),
    ]:
        try:
            for cap in fn():
                registry[cap.name] = cap
        except Exception as e:
            # Fail loud. A category that can't load silently dropped from
            # the output file produces a corrupted ``_generated_capabilities.json``
            # — capability entries vanish, parent units in the knowledge
            # store end up referencing missing children, and the DAG
            # validator surfaces dangling-ref warnings on every gateway
            # boot. The right response is to refuse to write a partial
            # file and force the developer to fix their environment
            # (typically: a missing optional dependency that this
            # category's imports require).
            raise RuntimeError(
                f"knowledge.build: category {label!r} failed to load "
                f"({type(e).__name__}: {e}). The auto-generated capability "
                f"file is the source of truth for the knowledge store; "
                f"writing a partial file would silently drop every "
                f"capability in this category and break parent-child "
                f"references in the store. This almost always means a "
                f"missing optional dependency — run the build from the "
                f"complete 'work-buddy' conda environment, which has "
                f"them all:\n"
                f"    conda run -n work-buddy python -m work_buddy.knowledge.build --write\n"
                f"(If 'conda' is not on PATH, use the env's interpreter "
                f"directly: <conda-or-miniforge>/envs/work-buddy/python — "
                f"see CLAUDE.md, 'Running Python in this repo'.)"
            ) from e

    _UNFILTERED = registry
    logger.info("Unfiltered registry: %d entries", len(registry))
    return registry
_STORE_DIR = _REPO_ROOT / "knowledge" / "store"

# Map registry categories to store path prefixes
_CATEGORY_PATH_MAP = {
    "tasks": "tasks",
    "contracts": "contracts",
    "projects": "projects",
    "journal": "journal",
    "context": "context",
    "memory": "memory",
    "messaging": "messaging",
    "notifications": "notifications",
    "consent": "notifications/consent",
    "conversations": "conversations",
    "status": "status",
    "sidecar": "status",
    "llm": "status",
    "artifacts": "artifacts",
    "operations": "operations",  # retry / obsidian_retry (category "operations")
}


def build_capability_units() -> dict[str, dict[str, Any]]:
    """Generate CapabilityUnit dicts from the MCP registry.

    Uses _build_registry_unfiltered() to include ALL capabilities,
    even those whose tool requirements (Obsidian, Hindsight, etc.)
    aren't currently met. The store should document everything,
    not just what's available right now.
    """
    from work_buddy.mcp_server.registry import Capability
    reg = _get_unfiltered_registry()
    units: dict[str, dict[str, Any]] = {}

    for name, entry in sorted(reg.items()):
        if not isinstance(entry, Capability):
            continue

        category = entry.category
        prefix = _CATEGORY_PATH_MAP.get(category, category)
        path = f"{prefix}/{name}"

        unit: dict[str, Any] = {
            "kind": "capability",
            "name": _humanize(name),
            "description": entry.description,
            "capability_name": name,
            "category": category,
        }

        if entry.search_aliases:
            unit["aliases"] = entry.search_aliases
        if entry.parameters:
            unit["parameters"] = entry.parameters
        if entry.requires:
            unit["requires"] = entry.requires
        if entry.invokes:
            unit["invokes"] = entry.invokes
        if entry.mutates_state:
            unit["mutates_state"] = True
            unit["retry_policy"] = entry.retry_policy

        # Check for consent requirement
        if hasattr(entry.callable, '_requires_consent'):
            unit["consent_required"] = True

        # Tags from category + name parts
        unit["tags"] = _name_to_tags(name, category)

        # Parent path
        unit["parents"] = [prefix]

        units[path] = unit

    return units


def build_parent_stubs(
    cap_units: dict[str, dict],
) -> dict[str, dict[str, Any]]:
    """Generate parent container nodes for categories that don't have them yet.

    Computes the FULL set of parent stubs required by the generated
    capability units — any parent not present in a HAND-AUTHORED store
    file gets a stub. Does NOT treat the previously-written
    ``_generated_parents.json`` as "already exists"; otherwise the
    wholesale rewrite in ``build_all`` would silently drop any parent
    not referenced by freshly-generated caps on this run. Without this
    filter, running ``build --write`` while a new parent is being added
    (e.g. ``artifacts``) would wipe all the other container stubs.
    """
    from work_buddy.knowledge.store import load_store

    existing = load_store()

    # Exclude paths that came from _generated_parents.json itself —
    # we're about to overwrite that file, so its current contents
    # must not be treated as "already exists in the hand-authored store."
    gen_parents_path = _STORE_DIR / "_generated_parents.json"
    if gen_parents_path.exists():
        try:
            prior_gen = json.loads(gen_parents_path.read_text(encoding="utf-8"))
            for p in prior_gen:
                existing.pop(p, None)
        except Exception:
            pass  # malformed file — treat as if absent

    all_units = {**cap_units}

    # Collect all parent paths referenced
    parent_paths: dict[str, list[str]] = {}
    for path, unit in all_units.items():
        for parent in unit.get("parents", []):
            parent_paths.setdefault(parent, []).append(path)

    stubs: dict[str, dict[str, Any]] = {}
    for parent_path, child_paths in parent_paths.items():
        if parent_path in existing:
            # Parent already exists in hand-authored store — skip
            continue
        if parent_path in stubs:
            # Already created a stub — just extend children
            stubs[parent_path]["children"] = sorted(
                set(stubs[parent_path].get("children", []) + child_paths)
            )
            continue

        stub_kind = (
            "system" if parent_path in _SYSTEM_PARENT_DOMAINS else "concept"
        )
        stubs[parent_path] = {
            "kind": stub_kind,
            "name": _humanize(parent_path.rsplit("/", 1)[-1]),
            "description": f"{_humanize(parent_path.rsplit('/', 1)[-1])} capabilities and workflows",
            "tags": [parent_path.replace("/", " ")],
            "children": sorted(child_paths),
            "content": {
                "summary": f"Container for {len(child_paths)} capabilities and workflows.",
            },
        }

    return stubs


def _humanize(name: str) -> str:
    """Convert slug to human-readable: task_create → Task Create."""
    return name.replace("_", " ").replace("-", " ").title()


def _name_to_tags(name: str, category: str) -> list[str]:
    """Extract search tags from a capability/workflow name."""
    parts = name.replace("-", "_").split("_")
    tags = [category] + [p for p in parts if p != category]
    return list(dict.fromkeys(tags))  # dedupe preserving order


def reconcile_handauthored_children(cap_units: dict[str, dict]) -> int:
    """Add auto-generated capability paths to hand-authored parents' ``children``.

    Hand-authored parent units (e.g. ``memory``) declare their own ``children``
    list. Auto-generated capabilities declare ``parents: [...]`` pointing at
    those parents. Without reconciliation, the hand-authored parent's
    children list goes stale relative to the live registry — capabilities
    exist in the store but are missing from the parent's children, breaking
    nav rendering for that subtree.

    This pass walks every generated capability and ensures its declared
    parents (when hand-authored, not auto-stub) include the capability path
    in their ``children`` list. Only adds; never removes — so hand-authored
    children that aren't auto-generated (siblings, sub-systems) survive.

    Returns the number of hand-authored parent files modified.
    """
    from work_buddy.knowledge.store import load_store

    store = load_store()

    # Index hand-authored files by path
    gen_paths: set[str] = set()
    for json_file in _STORE_DIR.glob("_generated_*.json"):
        try:
            data = json.loads(json_file.read_text(encoding="utf-8"))
            gen_paths.update(data.keys())
        except Exception:
            continue

    # For each capability, find its hand-authored parents and add it to their children
    additions: dict[str, set[str]] = {}  # parent_path -> {child_path, ...}
    for cap_path, cap_data in cap_units.items():
        for parent_path in cap_data.get("parents", []):
            # Skip if parent doesn't exist or is itself auto-generated
            if parent_path not in store or parent_path in gen_paths:
                continue
            additions.setdefault(parent_path, set()).add(cap_path)

    if not additions:
        return 0

    # Walk hand-authored files and merge in the discovered children
    files_modified = 0
    for json_file in _STORE_DIR.glob("*.json"):
        if json_file.name.startswith("_generated_"):
            continue
        try:
            data = json.loads(json_file.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            continue
        changed = False
        for parent_path, new_children in additions.items():
            if parent_path not in data:
                continue
            existing = set(data[parent_path].get("children", []))
            merged = existing | new_children
            if merged != existing:
                data[parent_path]["children"] = sorted(merged)
                changed = True
        if changed:
            json_file.write_text(
                json.dumps(data, indent=2, ensure_ascii=False) + "\n",
                encoding="utf-8",
            )
            files_modified += 1

    return files_modified


def build_all(write: bool = False) -> dict[str, Any]:
    """Build all generated units and optionally write to store files.

    Generates capability entries only. Workflow definitions live in
    knowledge/store/workflows.json as hand-authored content.
    """
    caps = build_capability_units()
    stubs = build_parent_stubs(caps)

    result = {
        "capabilities": len(caps),
        "parent_stubs": len(stubs),
    }

    if write:
        _STORE_DIR.mkdir(parents=True, exist_ok=True)

        # Write capabilities
        cap_path = _STORE_DIR / "_generated_capabilities.json"
        cap_path.write_text(json.dumps(caps, indent=2, ensure_ascii=False), encoding="utf-8")
        result["capabilities_file"] = str(cap_path)

        # Write parent stubs — always overwrite, since build_parent_stubs
        # computes the complete required set (not just newly-needed ones).
        stub_path = _STORE_DIR / "_generated_parents.json"
        stub_path.write_text(json.dumps(stubs, indent=2, ensure_ascii=False), encoding="utf-8")
        result["parents_file"] = str(stub_path)

        # Reconcile hand-authored parents with newly-generated capability children.
        # Must run after generated files are written, since reconcile reads the
        # live store to know which paths are auto-generated.
        from work_buddy.knowledge.store import invalidate_store
        invalidate_store()
        modified = reconcile_handauthored_children(caps)
        result["handauthored_parents_updated"] = modified

        logger.info(
            "Generated store files: %d capabilities, %d parent stubs, %d hand-authored parents updated",
            len(caps), len(stubs), modified,
        )

    return result


if __name__ == "__main__":
    write = "--write" in sys.argv
    docs = "--docs" in sys.argv
    result = build_all(write=write)

    if docs:
        # Also generate documentation site
        from work_buddy.knowledge.store import invalidate_store
        invalidate_store()  # reload with freshly generated store files
        from work_buddy.knowledge.docs_gen import generate_docs
        docs_result = generate_docs(write=write)
        result["docs"] = docs_result

    print(json.dumps(result, indent=2))
