"""Data models for the agent-user conversation system.

A Conversation groups ConversationMessages into a chronological dialogue
between an agent and a user. Any subsystem can create and use
conversations.

Renamed from ``work_buddy.threads`` — the ``Thread`` name is reserved
for the universal-entity primitive in :mod:`work_buddy.threads`.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class ConversationMessage:
    """A single message within a conversation.

    Attributes:
        message_id: Unique identifier (auto-generated by store).
        conversation_id: Parent conversation.
        role: Who sent this — "agent", "user", or "system".
        content: Message text (markdown supported).
        created_at: ISO 8601 timestamp.
        message_type: "text" (informational) or "question" (expects response).
        response_type: For questions — "freeform", "boolean", "choice", "none".
        choices: For choice questions — [{key, label, description?}].
        response: User's answer (filled when user responds).
        status: "sent" | "pending" (awaiting response) | "answered".
    """

    message_id: str = ""
    conversation_id: str = ""
    role: str = "agent"
    content: str = ""
    created_at: str = ""
    message_type: str = "text"
    response_type: str = "none"
    choices: list[dict] | None = None
    response: str | None = None
    status: str = "sent"

    def is_question(self) -> bool:
        return self.message_type == "question"

    def is_pending(self) -> bool:
        return self.status == "pending"

    def to_dict(self) -> dict[str, Any]:
        return {
            "message_id": self.message_id,
            "conversation_id": self.conversation_id,
            "role": self.role,
            "content": self.content,
            "created_at": self.created_at,
            "message_type": self.message_type,
            "response_type": self.response_type,
            "choices": self.choices,
            "response": self.response,
            "status": self.status,
        }

    @classmethod
    def from_row(cls, row: dict) -> ConversationMessage:
        """Create from a sqlite3 Row dict."""
        import json

        choices = row.get("choices")
        if isinstance(choices, str) and choices:
            choices = json.loads(choices)
        return cls(
            message_id=row["message_id"],
            conversation_id=row["conversation_id"],
            role=row["role"],
            content=row["content"],
            created_at=row["created_at"],
            message_type=row.get("message_type", "text"),
            response_type=row.get("response_type", "none"),
            choices=choices,
            response=row.get("response"),
            status=row.get("status", "sent"),
        )


@dataclass
class Conversation:
    """A conversation between an agent and a user.

    Attributes:
        conversation_id: Unique identifier (auto-generated by store).
        title: Display title.
        status: "open" or "closed".
        created_at: ISO 8601 timestamp.
        updated_at: ISO 8601 timestamp (updated on new messages).
        source: Who created this (e.g., "agent:<session_id>").
        metadata: Arbitrary dict for consumer context.
    """

    conversation_id: str = ""
    title: str = ""
    status: str = "open"
    created_at: str = ""
    updated_at: str = ""
    source: str = ""
    metadata: dict = field(default_factory=dict)

    def is_open(self) -> bool:
        return self.status == "open"

    def to_dict(self) -> dict[str, Any]:
        return {
            "conversation_id": self.conversation_id,
            "title": self.title,
            "status": self.status,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
            "source": self.source,
            "metadata": self.metadata,
        }

    @classmethod
    def from_row(cls, row: dict) -> Conversation:
        """Create from a sqlite3 Row dict."""
        import json

        metadata = row.get("metadata")
        if isinstance(metadata, str) and metadata:
            metadata = json.loads(metadata)
        elif not metadata:
            metadata = {}
        return cls(
            conversation_id=row["conversation_id"],
            title=row["title"],
            status=row.get("status", "open"),
            created_at=row["created_at"],
            updated_at=row.get("updated_at", ""),
            source=row.get("source", ""),
            metadata=metadata,
        )
