"""Artifact registration for the summarization framework's durable store.

The summary DB at ``<data_root>/summarization/summarization.db`` holds
LLM-generated summaries (one `summary_items` row per item + per-node
`summary_nodes` rows). Summaries are derived — they can be regenerated by
the producer cron — so retention is **infinite** by intent (no automatic
eviction; the artifact-cleanup tick sees it in the registry but never
prunes rows).

When a `summary_items` row is deleted, drop its child `summary_nodes` in
the same transaction so the tree stays consistent without relying on
SQLite FK enforcement.

The registration runs at package-import time — importing
``work_buddy.summarization`` is sufficient to make the artifact appear in
``artifact_registry_dump``. Mirrors the conversation-observability pattern.
"""

from __future__ import annotations

import logging

logger = logging.getLogger(__name__)


def register_summarization_artifact() -> None:
    """Register the ``summarization`` artifact.

    Defensive try/except: a failure inside the artifact subsystem must
    not cascade into making ``work_buddy.summarization`` uninstallable.
    """
    try:
        from work_buddy.artifacts import (
            Artifact,
            INFINITE_LIFECYCLE,
            SqliteRowsStorage,
            register_artifact,
        )
        from work_buddy.summarization.db import db_path

        register_artifact(Artifact(
            name="summarization",
            storage=SqliteRowsStorage(
                db_path=db_path(),
                table="summary_items",
                id_column="item_id",
                # Cascade child node rows when an item is deleted.
                post_delete_sql=[
                    "DELETE FROM summary_nodes "
                    "WHERE (namespace, item_id) NOT IN "
                    "(SELECT namespace, item_id FROM summary_items)",
                ],
                vacuum_on_delete=False,
            ),
            lifecycle=INFINITE_LIFECYCLE,
        ))
    except Exception as exc:  # pragma: no cover — defensive
        logger.warning(
            "Failed to register summarization artifact: %s", exc,
        )
